version: '3.7'
services:
  rails:
    build: .
    ports:
      - 3000:3000
    command: bundle exec puma -C config/puma.rb
    environment:
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_ENV: "development"
      DATABASE_HOST: "mysql"
      REDIS_URL: "redis://redis:6379/0"
    volumes:
      - rails_sockets:/app/tmp/sockets
      - ./:/app

  nginx:
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - rails_sockets:/app/tmp/sockets:ro

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: handson_development
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:5.0.6-alpine
    ports:
      - 6379:6379

volumes:
  rails_sockets:
    driver: local
  mysql_data:
    driver: local

